doorman/api.py
doorman/utils.py
tests/test_functional.py

This PR adds support for consuming osquery results in both [event](https://osquery.readthedocs.org/en/stable/deployment/logging/#event-format) and [batch](https://osquery.readthedocs.org/en/stable/deployment/logging/#batch-format) formats.
Result events are normalized to batch format for storing in Doorman's database. This allows organizations to continue to use the event based format if they plan to forward results to Elasticsearch, Splunk, et al.

Support both the result event and batch formats

---

doorman/api.py
doorman/app_extensions.py
doorman/application.py
doorman/compat.py
doorman/extensions.py
doorman/plugins/logs/base.py
doorman/plugins/logs/file.py
doorman/settings.py
doorman/utils.py
tests/test_utils.py

This adds the concept of custom logger plugins, and the ability to specify custom ones in a configuration.  I added an example one that lives in `doorman.plugins.logs.file`, which will log lines to a file in a format that can be read by, e.g. Splunk.
The nice thing is, you can add custom plugins by just ensuring that the package that contains the plugin is installed, and then specifying the import path to it - it can live outside of `doorman` itself.
Once we have the concept of "alerts", you could see adding a similar thing for those - plugins that can receive alerts and, e.g. dispatch to PagerDuty, Slack, email, and so on.

Initial thoughts on custom logger plugins

---

migrations/versions/71ef6e2ffb5b_.py
migrations/versions/a7c48850e100_.py

Change these to JSONB rather than using a fake JSONBType

---

.travis.yml
doorman/application.py
doorman/extensions.py
doorman/settings.py
doorman/tasks.py
doorman/worker.py
requirements/dev.txt
requirements/prod.txt
tests/test_celery.py

Add Celery support for running background tasks

---

doorman/api.py
doorman/application.py
doorman/extensions.py
doorman/settings.py
requirements/dev.txt
requirements/prod.txt

Use [scales](https://github.com/Cue/scales) to provide API request count and latency measurements.

Instrument API endpoints for metering and latency measurements

---

doorman/application.py
doorman/settings.py
doorman/templates/401.html
doorman/templates/403.html
doorman/templates/404.html
doorman/templates/500.html
doorman/templates/manage/_query.html
doorman/templates/manage/files.html
doorman/templates/manage/node.html
doorman/templates/manage/packs.html
doorman/templates/manage/queries.html
doorman/templates/manage/tables/distributed.html
doorman/templates/manage/tables/nodes.html
doorman/templates/manage/tables/packs.html
doorman/templates/manage/tags.html
doorman/templates/nav.html
doorman/views.py
manage.py

begin work against #25.
- ~~add tests~~
- ~~explore use of flask-logconfig extension for configuring logging~~
edit: nothing to really test here, and flask-logconfig seemed like overkill here.

register error handlers, change default config to production

---

.travis.yml
doorman/templates/manage/_activity.html
doorman/templates/manage/activity.html
doorman/templates/manage/distributed.result.html
doorman/worker.py
manage.py

Also, some minor ux tweaks to make navigating between nodes, distributed results, and recent activity.

Celery needs to know which config to load based on DOORMAN_ENV

---

doorman/plugins/alerters/pagerduty.py
doorman/utils.py
tests/test_alerters.py
tests/test_utils.py

Also, add tests (which I should have done from the start...)

Fix PagerDuty alerter

---

doorman/manage/views.py
doorman/templates/manage/activity.html
doorman/templates/manage/logs.html
doorman/templates/manage/node.html
doorman/templates/manage/tables/distributed.html
doorman/templates/manage/tables/logs.html
doorman/utils.py

Provide a view into a node's status logs.

Status log views

---

README.md
doorman/application.py
doorman/extensions.py
doorman/models.py
doorman/plugins/alerters/emailer.py
doorman/settings.py
doorman/templates/email/alert.body.txt
doorman/templates/email/alert.subject.txt
requirements/dev.txt
requirements/prod.txt
tests/conftest.py
tests/factories.py
tests/test_alerters.py

This plugin provides the ability to alert via email when a rule match triggers.

Email alert plugin

---

doorman/templates/manage/_query.html
doorman/templates/manage/files.html
doorman/templates/manage/node.html
doorman/templates/manage/packs.html
doorman/templates/manage/tables/nodes.html
doorman/templates/manage/tables/packs.html
doorman/templates/manage/tags.html

Sort tags when displaying

---

.dockerignore
Dockerfile
README.md
docker/default-settings.cfg
docker/redis.conf
docker/service/api/run
docker/service/celery/run
docker/service/redis/run

I don't know Docker that well, but this seems to work?

Initial work on running in Docker

---

doorman/manage/forms.py
doorman/templates/manage/packs.html
doorman/templates/manage/queries.html
doorman/templates/manage/rules.html

Add scrollspy style nav to rules page.
Also, add "ubuntu" as a possible platform in the select dropdown.

Rules scrollspy

---

doorman/manage/views.py
doorman/templates/manage/distributed.html
doorman/templates/manage/distributed_results.html
doorman/templates/manage/tables/distributed.html
doorman/templates/manage/tables/distributed_results.html
tests/test_functional.py

Includes some basic tests (though maybe we should pull in a real HTML parser and use that instead...)

Allow viewing the results for only a single distributed query

---

doorman/static/js/plugins.js
doorman/templates/manage/_query.html
doorman/templates/manage/files.html
doorman/templates/manage/node.html
doorman/templates/manage/packs.html
doorman/templates/manage/tables/nodes.html
doorman/templates/manage/tables/packs.html

Also adds the hash to the URL when switching between recent activity.

Add input placeholder to indicate where users can enter tags

---

doorman/extract_ddl.py
manage.py

Fixed several Python3 compatibility issues regarding extract_ddl command

Couple fixes

---

doorman/plugins/logs/file.py
doorman/plugins/logs/logstash.py
doorman/settings.py

This PR adds a log plugin to emit osquery result and status records to a JSON log, suitable for Logstash.

Logstash logger

---

doorman/compat.py
doorman/manage/views.py
requirements/dev.txt
requirements/prod.txt
setup.py
tests/test_functional.py

This PR fixes several issues with the CSV node download in Python3.

Fix csv node download in python 3

---

doorman/plugins/logs/file.py

Logs weren't showing up promptly for us, and this fixes it.

Properly flush the status / results file after handling

---

Dockerfile

Hi,
first of all, amazing project, i'm trying to implement here at work, but i'm still in testing phase,there is a small glitch on the Docker package now it build properly, let me know if it's ok and i hope to support the project more in the future :)

modified docker file to support update on alpine package for pip

---

doorman/plugins/logs/logstash.py

This fixes two bugs:
1. `os.fsync` takes an argument (the file descriptor to flush), so we give it that.
2. `for ... else ...` will only flush / fsync if nothing is found; we want `try ... finally` so it always does so.

Fix Logstash plugin

---

doorman/api.py
doorman/extensions.py
doorman/plugins/alerters/base.py
doorman/plugins/alerters/debug.py
doorman/plugins/alerters/emailer.py
doorman/plugins/alerters/pagerduty.py
doorman/plugins/alerters/sentry.py
doorman/tasks.py
doorman/templates/email/enroll.body.txt
doorman/templates/email/enroll.subject.txt
tests/test_alerters.py
tests/test_functional.py

Some much needed notifications to alert us when a new node comes online.

Send a notification when a node enrolls for the first time

---

doorman/plugins/alerters/slack.py
doorman/settings.py
tests/test_alerters.py

Slack alerter plugin that posts match results to a Slack channel via a webhook.

Slack alerter plugin

---

doorman/assets.py

Fix directory of interact.js
