- doorman/forms.py
- doorman/utils.py
- doorman/views.py
- tests/test_forms.py
We weren't validating sql when updating a query. This PR turns the sql validator into something more generally applicable to a WTForm. Plus more tests.
> Refactor the osquery sql validator into a WTForms style field validor

- doorman/plugins/logs/file.py
- doorman/utils.py
- tests/test_functional.py
The first entry in the data field may not be representative of all entries, so instead, the extract_results method has been refactored to handle each entry individually.
Todo: handle snapshot logs.
> refactor the way we process results

- MANIFEST.in
- doorman/api.py
- requirements/prod.txt
- setup.py
Flask-DebugToolbar is needed by the application (though can be explicitly enabled/disabled), and MANIFEST.in allows us to include the templates and other non-py files in our package.
> Add Flask-DebugToolbar to requirements and add a MANIFEST.in

- doorman/templates/manage/_activity.html
- doorman/templates/manage/activity.html
- doorman/templates/manage/nodes.html
- doorman/views.py
- requirements/dev.txt
- requirements/prod.txt
Added pagination to the nodes page, displaying a maximum of 20 nodes per page. Also use tabs to display and organize recent activity for a node, rather than dump it all together. 
Addresses most of #23. Some ui tweaks could be added to enable the ordering and sorting.
> Pagination and tabs

- doorman/application.py
If `DOORMAN_NO_MANAGER` environment variable is set, then Doorman will return an app containing only the API endpoints.
> Support deploying just the API by setting an env var

- manage.py
Useful for cases where you want to precompile the assets (i.e. not have NodeJS installed on the API server).
> Add manage.py command for assets

- doorman/templates/manage/_activity.html
Avoid CSS selector and jQuery/Bootstrap weirdness by just using the loop index rather than the pack/query name.
> Fix tab panel navigation

- doorman/rules.py
- tests/test_rules.py
This PR addresses a bug in the way we were retrieving column values for comparison. In this case, `self.key` will never return the value we're expecting, as it is set to `column` rather than the column name specified by the user. In the case where the result contains an actual `column` key, then this would result in unexpected behavior.
> Use column_name, not key when comparing column field

- doorman/plugins/alerters/pagerduty.py
This PR formats the PagerDuty incident with the rule's name and description (if available). Previously, the only information immediately visible was "A doorman alert was triggered", which was not really informative.
> Add rule description to pagerduty incident

- bower.json
- doorman/assets.py
- doorman/templates/manage/_activity.html
Way cleaner to display query results this way versus horizontally, causing tabs to spill over into multiple lines, pushing the actual content down the page.
> Display tabs vertically instead of horizontally

- doorman/manage/forms.py
- doorman/manage/views.py
- doorman/models.py
- doorman/templates/manage/files.html
- doorman/templates/manage/forms/file.html
- tests/test_models.py
Added an additional `set_paths` method on the `FilePath` model so that we don't have to think about serializing and deserializing the list of file paths.
Also support actually updating a category once it's been created.
> Add support for updating file paths

- doorman/plugins/logs/file.py
- doorman/rules.py
- doorman/templates/manage/_rule.html
- tests/test_rules.py
This PR fixes some issues we have with the empty/not empty rule operator, as well as flips the less (than) / greater (than) conditionals to be inline with what you'd expect during comparison.
Also fixes bug reported by @grantstavely in file logger plugin.
> Rule fixes

- doorman/extensions.py
- doorman/models.py
- doorman/plugins/alerters/pagerduty.py
- doorman/plugins/alerters/sentry.py
- doorman/settings.py
- doorman/templates/manage/forms/rule.html
- tests/conftest.py
- tests/test_alerters.py
This PR adds a new alerter for Sentry. The `doorman.plugins.alerts.sentry.SentryAlerter` alerter plugin will send alerts to Sentry if configured.
Additionally, this PR adds Sentry alerting to Celery, along with support for treating rule names and descriptions as template strings.
> Sentry alerter

- doorman/utils.py
- tests/test_functional.py
Addresses any `ValueError` or `KeyError` exceptions raised when uploading empty packs or packs with non-json data.
> Better pack upload error handling

- Dockerfile
Runit no longer appears to be in testing. When attempting to build the dockerfile on Ubuntu 16.04 and OSX 10.11, I received the following error:
```
Sending build context to Docker daemon 1.838 MB
Step 1 : FROM alpine:latest
---> 7d23b3ca3463
Step 2 : RUN apk update
---> Running in 2752fc94a38c
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
v3.4.3-66-gc73e68d [http://dl-cdn.alpinelinux.org/alpine/v3.4/main]
v3.4.3-62-gaaf1b40 [http://dl-cdn.alpinelinux.org/alpine/v3.4/community]
OK: 5968 distinct packages available
---> e004eba74087
Removing intermediate container 2752fc94a38c
Step 3 : RUN echo "@testing http://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories …
```
> Updating path to runit in Dockerfile

- bower.json
- doorman/assets.py
`Doorman` displays the following error in `/manage/rules/add`.
>query-builder.standalone.js:2943 Uncaught Error: interact.js is required to use "sortable" plugin. Get it here: http://interactjs.io
This is because `jQuery-QueryBuilder` implemented `interact.js`
https://github.com/mistic100/jQuery-QueryBuilder/commit/221eb4f9906659c85c8f9334d6724aafda601c83#diff-d23309cd66d33b4200455ba8287dbca4R11
I sent Pull Request to `jQuery-QueryBuilder` to move `interact` from `devDependencies` to `dependencies`.
https://github.com/mistic100/jQuery-QueryBuilder/pull/396
I received the following answer
>I put it in dev dependencies because it's not a required component for the basic use of the library, it's the same for every dependency of query builder plugins.
So, I think that `Doorman` should add …
> Add interact.js

- Dockerfile
Without this change the UI fails to load. File permissions errors are
thrown.
> Change file ownership to doorman in docker.

- docker/service/api/run
If DOORMAN_ENV is passed in via docker environment variable, use that.
> Don't force DOORMAN_ENV to prod in the docker config

- Dockerfile
When using the latest alpine-package, npm is not part of the nodejs package
anymore. Installing nodejs-npm will provide the npm binary.
> Fix Dockerfile: Add nodejs-npm package

- doorman/extensions.py
- doorman/plugins/alerters/base.py
- doorman/plugins/alerters/debug.py
- doorman/plugins/alerters/emailer.py
- doorman/plugins/alerters/pagerduty.py
- doorman/plugins/alerters/sentry.py
- doorman/settings.py
- doorman/tasks.py
- doorman/templates/email/enroll.body.txt
- doorman/templates/email/enroll.subject.txt
- doorman/utils.py
- tests/test_alerters.py
- tests/test_functional.py
Run nodes through our alert manager so that we can define within the Rule Manager alerts against the following info:
* action: `triggered`
* query name: `doorman/tasks/node_offline_checks`
* columns:
* `since_last_result`
* `since_last_result_days`
* `since_last_result_seconds`
* `since_last_checkin`
* `since_last_checkin_days`
* `since_last_checkin_seconds`
* `since_last_checkin_to_last_result`
* `since_last_checkin_to_last_result_days`
* `since_last_checkin_to_last_result_seconds`
For example, a decent start might be to alert when a node last checked in or submitted a result more than 7 days ago, and alert if the time between the last result and the last check is more than 2 days.
This catches those instances where a node completely goes offline, or rocksdb gets corrupted. In the latter …
> Periodically check when a node last checked in and submitted results

- doorman/models.py
- doorman/plugins/alerters/emailer.py
- tests/test_alerters.py
Render email as jinja2 template, then perform safe string substitution on body and subject
* replaces $'s with values from the node attributes or column fields in a result
https://www.python.org/dev/peps/pep-0292/
> Support simple string subsitutions in email alerts

- doorman/manage/views.py
- doorman/templates/manage/results.html
- doorman/templates/manage/tables/results.html
This provides the very beginnings for a search API. Results can be queried by passing any number of query string parameters, i.e., `/manage/search?columns.removable=1&columns.usb_port=5&columns.usb_port=12`, would return all results where `removable=1 AND (usb_port=5 OR usb_port=12)`. The idea here is you can click on an existing key/value in a table and it'll perform a search across all results for that key/value pair, and try to normalize the results. This allows you to quickly query the results table for nodes that returned the same key/values.
I don't think it's worth expanding too much effort into making the query syntax anymore sophisticated, as that'd likely require writing a DSL, and frankly, there are better tools for the job (e.g., Elasticsearch).
Some work could be done on the …
> [WIP] Beginnings of a search api
